### ISSUE TITLE
Feature Request: Dense Stone Generation Mode

### ISSUE THREAD

**Issue by rehashedsalt** [yungnickyoung/YUNGs-Law#1]
Opening this in light of [random cool idea on reddit](https://www.reddit.com/r/feedthebeast/comments/i2dtak/i_made_a_mod_that_prevents_strip_mining_and/g04fhw7/):

>It would be interesting to create a dense stone block that only generates 10 blocks away from caves. This dense stone block is a PITA to mine by hand, but easy to mine using quarries. End game ores only generate in dense stone, soft gating those ores behind quarries.

It would be nice for the mod to feature a spin-off of the obsidian generation mode where, instead of obsidian, it generates a more dense variant of stone with a configurable hardness. It accomplishes the same goal, but keeps obsidian scarce.

In addition to its tech pack applications, this could give a use for extremely fast pickaxes in exploration or magic packs and encourage the use of powerful explosives (if available).

The heavy lifting for oregen would be done elsewhere in a mod like CoFH World.

**Comment by yungnickyoung** [comment]
Someone's response was this: 

> Have you looked at Ore Stone Variants? That would be an easy way to generate end game ores only in dense stone, which you could add with ContentTweaker. Then use the config from this mod to replace Obsidian with Dense Stone.

Would that be what you're looking for?

**Comment by rehashedsalt** [comment]
Yeah, that'd be a sufficient solution for basically all of the use cases I've given. Didn't realize there was already a config for hardBlock.
